library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/vimaleshn98/jenkins-pipeline-demo-library.git'])

simplePipeline()