pipeline {
    agent {
        dockerfile {
            dir 'm4'
        }
    }
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
        DOTNET_CLI_HOME = "/tmp/DOTNET_CLI_HOME"
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                  dotnet --list-sdks
                  dotnet --list-runtimes
                '''
            }
        }   
        stage('Smoke Test') {
            steps {
              sh 'docker run sixeyed/pi:psod-pipelines'
            }
        }
    }
}